name: Go Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-release:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Build release artifacts using Makefile
        run: make release VERSION=${{ env.VERSION }}

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ env.VERSION }}
          body: |
            Release of version ${{ env.VERSION }}
            *Automated release via GitHub Actions*
          draft: false
          prerelease: ${{ contains(github.ref_name, '-') }}
          files: |
            build/release/*
